spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  cloud:
    discovery:
      client:
        simple:
          instances:
            product-service:
              - uri: http://localhost:8083
            compatibility-service:
              - uri: http://localhost:8085
            notification-service:
              - uri: http://localhost:8090

eureka:
  client:
    enabled: false

app:
  environment: development

logging:
  level:
    cl.tarrobuild: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG