spring:
  application:
    name: build-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}

server:
  port: ${SERVER_PORT:8087}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8083}

compatibility-service:
  url: ${COMPATIBILITY_SERVICE_URL:http://localhost:8085}

app:
  environment: production

logging:
  level:
    cl.tarrobuild: INFO
    org.hibernate.SQL: WARN
  file:
    name: logs/build-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

feign:
  client:
    connect-timeout: 5
    read-timeout: 10