spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_builds}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true

logging:
  level:
    root: WARN
    cl.tarrobuild: INFO
    org.springframework: WARN
  file:
    name: /var/log/build-service/build-service.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30