spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true
    schemas: product
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: product
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-render.sql

category-service:
  url: ${CATEGORY_SERVICE_URL:http://localhost:8084}

app:
  environment: production

logging:
  level:
    cl.tarrobuild: INFO
    org.hibernate.SQL: WARN
  file:
    name: logs/product-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
