spring:
  application:
    name: compatibility-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}

server:
  port: ${SERVER_PORT:8085}

restclient:
  connect-timeout: 5000
  read-timeout: 10000

app:
  environment: ${APP_ENVIRONMENT:development}

logging:
  level:
    cl.tarrobuild.compatibility: DEBUG
    org.springframework.web: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
