spring:
  application:
    name: hardware-advisor-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}

server:
  port: ${SERVER_PORT:8089}

app:
  environment: production

logging:
  level:
    cl.tarrobuild: INFO
    org.hibernate.SQL: WARN
  file:
    name: logs/hardware-advisor-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

feign:
  client:
    connect-timeout: 5
    read-timeout: 10

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
